//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicDiary.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> DisciplineId { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Students Students { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
